### PR TITLE
Actions

### PR DESCRIPTION
**Pull request by jburel**
Replace travis by GHA
see https://github.com/jburel/ice-builder-gradle/actions/runs/411544568

### CODE REVIEW

**Comment by joshmoore** [comment]
Were tests failing and therefore need omitting?  Or worse, is it that `publishToMavenLocal` doesn't run `test`?! If so, that could show up all kinds of interesting surprises.

**Comment by jburel** [comment]
``publishToMavenLocal`` does not run the tests.
The tests were never run including on the zeroc-ice repo (this is a fork) and some are failing
we never spent time working on those tests.
This can be done in a follow-up PR.

**Comment by jburel** [comment]
I finally managed to get the tests green (nothing is working in upstream repo!)
https://github.com/jburel/ice-builder-gradle/actions/runs/480259081
is green

**Comment by joshmoore** [comment]
Wow. Nice. Thanks, J-m. Looks good. :+1:

**Pull request merged**
