### PR TITLE
gradle 6

### PR DESCRIPTION
**Pull request by jburel**
This PR makes changes so it can be built with newer version of gradle
tested locally with 6.6. GHA will run with 6.8

### CODE REVIEW

**Comment by joshmoore** [comment]
Speaking for a number of gradle PRs (https://github.com/ome/omero-api-plugin/pull/11, https://github.com/ome/omero-dsl-plugin/pull/16, https://github.com/ome/omero-blitz-plugin/pull/16) none of the changes look particularly onerous. Probably by biggest question is what range of gradle versions are now supported?

**Comment by sbesson** [comment]
Two addition questions from my side, also applicable to all Gradle PRs

- is one of the goals to also remove the hardcoded version from https://github.com/ome/.github/blob/master/workflow-templates/gradle.yml when all the repos are updated?
- will this be deployed to https://artifacts.openmicroscopy.org/ or Maven? By hand or via a GitHub workflow?

**Comment by jburel** [comment]
This PR will support gradle version 5 to 7. 
Other 5 and 6 only, since some changes required for gradle 7 no longer work with gradle 5 e.g. https://github.com/ome/omero-artifact-plugin/pull/13/commits/277de06ac974b3bdd2b0c5c47553429e735efba0. We will need for that to upgrade our infra to gradle 6 to include such change.
In the template, the version will be changed too but I still think we should keep the ability to set the version we want to build with so we can easily switch between versions. The fix in https://github.com/ome/.github/pull/18 should be included since now gradle 6 is not as permissive as gradle 5 during the configuration phase and the current template file will not work in some cases e.g. omero-blitz

Artifacts will still be deployed manually on artifactory. This is a different body of work.

**Comment by sbesson** [comment]
Summarizing my understanding of the next steps:

- merge this set of PRs adding support for Gradle 6.x
- manually release a set of (minor?) plugin releases to the OME Artifactory compatible with Gradle 5+
- start rolling out the latest Gradle plugin upgrades across all OME Gradle projects
- update GitHub workflows to test using Gradle 6.x
- look into upgrading devspace to build using Gradle 6.x

And potentially later, look into Gradle 7 which might require dropping Gradle 5 etc

Is that a correct representation @jburel? If so, no objections.

**Comment by jburel** [comment]
It is correct, I have already made changes to GHA to run with gradle6 and test the changes made in the plugins by the consumers i.e. https://github.com/ome/omero-model/pull/66 and https://github.com/ome/omero-blitz/pull/114

**Pull request merged**
