### PR TITLE
Updated SlicePlugin to auto configure versions of ice dependencies

### PR DESCRIPTION
**Pull request by rgozim**
Adds feature to resolve the version of ice dependencies.

For example, we can now use:

``` gradle
dependencies {
    implementation "com.zeroc:icestorm" // note the version misssing
}

```

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-gradle-plugins-push#11](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/11/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/11/consoleText) for more details.
Possible conflicts:
  - PR #10 rgozim 'Removed unused code'
    - src/main/groovy/com/zeroc/gradle/icebuilder/slice/SlicePlugin.groovy

--conflicts

**Comment by mtbc** [comment]
So for testing one removes the version from downstream "com.zeroc" stuff and sees if everything still works?

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-gradle-plugins-push#129](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/129/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/129/consoleText) for more details.
Possible conflicts:
  - PR #10 rgozim 'Removed unused code'
    - src/main/groovy/com/zeroc/gradle/icebuilder/slice/SlicePlugin.groovy

--conflicts

**Comment by rgozim** [comment]
> So for testing one removes the version from downstream "com.zeroc" stuff and sees if everything still works?

Yes. I probably should have added that to the description.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-gradle-plugins-push#130](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/130/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/130/consoleText) for more details.
Possible conflicts:
  - PR #10 rgozim 'Removed unused code'
    - src/main/groovy/com/zeroc/gradle/icebuilder/slice/SlicePlugin.groovy

~~--conflicts~~ Conflict resolved in build [OMERO-gradle-plugins-push#115](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/115/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-gradle-plugins-push/115/consoleText) for more details.

**Pull request closed without merging**
